# Generated by Django 2.1.2 on 2018-10-06 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=100)),
                ('library_code', models.CharField(max_length=100)),
                ('library_address', models.CharField(blank=True, max_length=1000)),
                ('lat', models.FloatField(blank=True, default=0)),
                ('lng', models.FloatField(blank=True, default=0)),
                ('library_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='movies.District')),
            ],
        ),
    ]
