# Generated by Django 2.1.3 on 2018-11-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=100)),
                ('library_code', models.CharField(max_length=100)),
                ('library_address', models.CharField(blank=True, max_length=1000)),
                ('lat', models.FloatField(blank=True, default=0)),
                ('lng', models.FloatField(blank=True, default=0)),
                ('library_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='movies.District')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('when', models.DateTimeField(blank=True)),
                ('place', models.CharField(blank=True, max_length=200)),
                ('runtime', models.CharField(blank=True, max_length=100)),
                ('director', models.CharField(max_length=200)),
                ('thumbnail_url', models.CharField(max_length=200)),
                ('story', models.TextField(blank=True)),
                ('age', models.CharField(blank=True, max_length=200)),
                ('rating', models.FloatField(blank=True, default=0)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.Library')),
            ],
        ),
    ]
