language: python
python:
- 3.6.5
services: postgresql

addons:
  postgresql: '9.4'

before_install:
- openssl aes-256-cbc -K $encrypted_cdad78b402c4_key -iv $encrypted_cdad78b402c4_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- export DJANGO_SETTINGS_MODULE=config.settings.production
install:
- pip install -r requirements.txt

branches:
  only:
  - master

cache: pip

before_script:
- psql -c 'create database travis_ci_db;' -U postgres

script:
- python app/manage.py test
- git add -A

before_deploy:
- zip -r archive.zip .

deploy:
  provider: elasticbeanstalk
  zip_file: archive.zip
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: ap-northeast-2
  app: EB Docker Deploy Movie
  env: EBDockerDeploy-Movie
  bucket_name: library-movie-travis-deploy
  skip_cleanup: true
  on:
    branch: master