language: python
python:
- 3.6.5
services: postgresql

addons:
  postgresql: '9.4'

before_install:
- openssl aes-256-cbc -K $encrypted_cdad78b402c4_key -iv $encrypted_cdad78b402c4_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- export DJANGO_SETTINGS_MODULE=config.settings.production
install:
- pip install -r requirements.txt

branches:
  only:
  - master

cache: pip

before_script:
- psql -c 'create database travis_ci_db;' -U postgres

script:
- python app/manage.py test