# Generated by Django 2.1.7 on 2019-03-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_created_at'),
        ('members', '0007_movielike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movie',
            field=models.ManyToManyField(through='members.MovieLike', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='set_alarm_before_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='set_alarm_before_3h',
            field=models.BooleanField(default=False),
        ),
    ]
