# Generated by Django 2.1.7 on 2019-04-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20190405_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='movie',
            field=models.ManyToManyField(blank=True, through='members.MovieLike', to='movies.Movie'),
        ),
    ]
